Add body structure
OrdinaryMack/Portfolio-Finish-mobile-version pull request #1
Opened 2023-10-07 13:19 UTC by OrdinaryMack

In this pull request
1. I created the mobile version body structure of Portfolio
2. Adding some styles with Css 
3. Add media query values according to project requirements
4. Add descriptive Readme 
5. Fixing some errors dealing with stylelints

2023-10-07 18:08 UTC, K0ppai requested changes
# Status: Changes Required♻️♻️♻️
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

# Hi @OrdinaryMack 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- All linter are passing ✔
- Use ul and li for categories in "Work" section. ✔️ 
- Descriptive pull request ✔️
- Good commit messages ✔️

## Required Changes ♻️
Kindly update your readme file to make it professional and check the following comments for required changes.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-10-07 18:08 UTC, K0ppai commented on index.html
> +    <section class="work-card">
Hello @OrdinaryMack,
Even though you've done a great job using the CSS Grid 👍, I think you've misunderstood the project requirements. You're using the grid in individual cards instead of the main container. Hint: you can use the **grid** in `work-card` class and use `flexbox` for each card.

![image](https://github.com/OrdinaryMack/Portfolio-Finish-mobile-version/assets/113283174/c4294e0b-b759-49df-a767-d6b433d5651c)

2023-10-07 18:08 UTC, K0ppai commented on index.html
> +    </section>
Kindly stick to the Figma design as much as possible. **Hint:** You can build the design to match the mobile version first then adapt it to the desktop version.
### **Your design:**
![image](https://github.com/OrdinaryMack/Portfolio-Finish-mobile-version/assets/113283174/42daa739-cde3-4eed-9eac-614f91cb60b2)
### **Figma Design:**
![image](https://github.com/OrdinaryMack/Portfolio-Finish-mobile-version/assets/113283174/d83d5a3c-00e1-47aa-9e9d-2bf28bcd475a)

2023-10-07 18:08 UTC, K0ppai commented on index.html
> +</section>
Kindly fix it to match the Figma design as much as possible. **Hint:** You can build the design to match the mobile version first then adapt it to the desktop version. 
### **Your Design:**
![image](https://github.com/OrdinaryMack/Portfolio-Finish-mobile-version/assets/113283174/7f806e68-4ec0-4976-9a45-069589bc050d)
### **Figma Design:**
![image](https://github.com/OrdinaryMack/Portfolio-Finish-mobile-version/assets/113283174/960060ac-e7c2-4d62-bb01-b50d14d1b6f5)

2023-10-07 18:08 UTC, K0ppai commented on index.html
> +        </div>
Kindly use `ul` and `li` tags for the `Languages`, `Frameworks`, and `Skills` due to this project requirement.

![image](https://github.com/OrdinaryMack/Portfolio-Finish-mobile-version/assets/113283174/19bbbe70-bcf2-48da-b1b2-6e488de03fed)

2023-10-11 18:59 UTC, painghtetaung commented
[optional] - I just wanted to let you know that when naming assets, such as images, it's best to use all lowercase letters and avoid spaces. Instead, you can use underscores or dashes to make file names more clear and user-friendly when importing them.

2023-10-11 19:01 UTC, painghtetaung commented
## STATUS: APPROVED 🟢

## Hi 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

2023-10-11 19:02 UTC, painghtetaung approved these changes
## STATUS: APPROVED 🟢

## Hi 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

2023-10-11 19:02 UTC, painghtetaung commented on index.html
> +            </div>
[optional] - Delete this unnecessary div

2023-10-12 14:44 UTC, merged